# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AnalyzerRpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x41nalyzerRpc.proto\x12\x0b\x41nalyzerRpc\"\x1f\n\x0cInputMessage\x12\x0f\n\x07payload\x18\x01 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32I\n\x08\x41nalyzer\x12=\n\x07\x41nalyze\x12\x19.AnalyzerRpc.InputMessage\x1a\x15.AnalyzerRpc.Response\"\x00\x62\x06proto3')



_INPUTMESSAGE = DESCRIPTOR.message_types_by_name['InputMessage']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
InputMessage = _reflection.GeneratedProtocolMessageType('InputMessage', (_message.Message,), {
  'DESCRIPTOR' : _INPUTMESSAGE,
  '__module__' : 'AnalyzerRpc_pb2'
  # @@protoc_insertion_point(class_scope:AnalyzerRpc.InputMessage)
  })
_sym_db.RegisterMessage(InputMessage)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'AnalyzerRpc_pb2'
  # @@protoc_insertion_point(class_scope:AnalyzerRpc.Response)
  })
_sym_db.RegisterMessage(Response)

_ANALYZER = DESCRIPTOR.services_by_name['Analyzer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INPUTMESSAGE._serialized_start=34
  _INPUTMESSAGE._serialized_end=65
  _RESPONSE._serialized_start=67
  _RESPONSE._serialized_end=93
  _ANALYZER._serialized_start=95
  _ANALYZER._serialized_end=168
# @@protoc_insertion_point(module_scope)
